sample_app-master/config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "password_resets/new"
  get "password_resets/edit"
  get "sessions/new"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, except: [:index, :show, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

sample_app-master/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   <%= t("layout.footer.announce_small_html",
     href1: link_to(t("layout.footer.rails_tutorial"),
     t("layout.footer.link_rails_tutorial")),
     href2: link_to(t("layout.footer.michael_hartl"),
     t("layout.footer.link_michael_hartl"))) %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("layout.footer.about"), about_path %></li>
      <li><%= link_to t("layout.footer.contact"), contact_path %></li>
      <li><%= link_to t("layout.footer.news"), t(".link_news") %></li>
    </ul>
  </nav>
</footer>

sample_app-master/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layout.header.sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("layout.header.home"), root_path %></li>
        <li><%= link_to t("layout.header.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("layout.header.users"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t("layout.header.account") %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("layout.header.profile"), current_user %></li>
              <li>
                <%= link_to t("layout.header.settings"),
                  edit_user_path(current_user) %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to t("layout.header.log_out"), logout_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("layout.header.log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

sample_app-master/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

sample_app-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>